Implement "Description trick" and "Date replace"

diff --git a/msmtpq b/msmtpq
--- a/msmtpq
+++ b/msmtpq
@@ -272,7 +272,7 @@ ok() {
 ## send a queued mail out via msmtp
 ##
 send_queued_mail() {   # <-- mail id
-  local FQP="${Q}/${1}"              # fully qualified path name
+  FQP="${Q}/${1}"              # fully qualified path name
   local -i RC=0                      # for msmtp exit code
 
   if [ -f "${FQP}.msmtp" ] ; then    # corresponding .msmtp file found
@@ -284,10 +284,21 @@ send_queued_mail() {   # <-- mail id
       }
     }
 
-  if [ ! -f "${FQP}.at" ] ; then    # corresponding .at file NOT found
-    echo -n $MSMTP $(< "${FQP}.msmtp")  "< ${FQP}.mail  && rm -f ${FQP}.* || rm -f ${FQP}.at"|at now + $DEFER_DELAY minutes && touch ${FQP}.at
-  fi
+  schedule_send_mail "$1" "$2"
 
+  fi                                                           # (but allow continuation)
+}
+
+schedule_send_mail() {
+  if [ ! -f "${FQP}.sch" ] ; then    # corresponding .sch file NOT found
+    if echo -n "sed -i \"s/^Date: .*/Date: \$(date -R)/\" ${FQP}.mail && "  $MSMTP $(< "${FQP}.msmtp")  "< ${FQP}.mail && rm -f ${FQP}.* && echo -n 'EMail sent successfully [${FQP}]' >> ${LOG} || echo -n 'ERROR sending the email [${FQP}]' >> ${LOG}"|at $(< "${FQP}.at") ; then # schedule sending the email from the pipeline with at
+      touch ${FQP}.sch  # put the "sch" parameter within the file
+      log "mail [ $2 ] [ $1 ] from queue ; scheduled successfully"  # good news to user
+      ALT='t'                        # set queue changed flag
+    else
+      RC=$?                          # take msmtp exit code
+      log "mail [ $2 ] [ $1 ] from queue ; scheduled failed ; msmtp rc = $RC; look at ${FQP}.at, modify it, and run msmtp-queue -r" # bad news ...
+    fi
   #  if $MSMTP $(< "${FQP}.msmtp") < "${FQP}.mail" ; then       # this mail goes out the door
   #    log "mail [ $2 ] [ $1 ] from queue ; send was successful ; purged from queue"  # good news to user
   #    'rm' -f ${FQP}.*                                         # nuke both queue mail files
@@ -301,7 +312,7 @@ send_queued_mail() {   # <-- mail id
   #  log "preparing to send .mail file [ $1 ] [ ${FQP}.mail ] but"\
   #      "  corresponding .msmtp file [ ${FQP}.msmtp ] was not found in queue"\
   #      '  skipping this mail ; this is worth looking into'    # give user the bad news
-  fi                                                           # (but allow continuation)
+  fi
 }
 
 ## run (flush) queue
@@ -489,9 +500,7 @@ send_mail() {    # <-- all mail args ; mail text via TMP
     }
   }
 
-  if [ ! -f "${FQP}.at" ] ; then    # corresponding .at file NOT found
-    echo -n $MSMTP $(< "${FQP}.msmtp")  "< ${FQP}.mail  && rm -f ${FQP}.* || rm -f ${FQP}.at"|at now + $DEFER_DELAY minutes && touch ${FQP}.at
-  fi
+  schedule_send_mail "$*" "${ID}"
 
  # if $MSMTP "$@" < "${FQP}.mail" > /dev/null ; then      # send mail using queue .mail fil
  #   log "mail for [ $* ] : send was successful"          # log it
@@ -502,6 +511,16 @@ send_mail() {    # <-- all mail args ; mail text via TMP
  #       "enqueued mail as : [ $ID ] ( $* )"    # (queue .mail file is already there)
  # fi
 }
+
+generate_at() {
+  if  grep -q "^Content-Description: " ${FQP}.mail  ; then # if a description header have been written
+    echo $(pcregrep -o1 "Content-Description: (.*)" "${FQP}.mail") # extract the at pattern
+    sed '/^Content-Description/d' "${FQP}.mail" # remove the Description line that won't be used anymore
+  else
+    echo "now + ${DEFER_DELAY} minutes" # set default delay
+  fi
+}
+
 
 #
 ## -- entry point
@@ -514,6 +533,7 @@ if [ ! "$1" = '--q-mgmt' ] ; then    # msmtpq - sendmail mode
   cat > "${FQP}.mail" || \
     log -e "$?" "creating mail body file [ ${FQP}.mail ] : failed" # test for error
   # write msmtp command line to queue .msmtp file
+  echo -n $(generate_at) > ${FQP}.at  # put the "at" parameter within the file
   echo "$@" > "${FQP}.msmtp" || \
     log -e "$?" "creating msmtp cmd line file { $* }"\
                 "           to [ ${ID}.msmtp ] : failed" # test for error
